name: Update Checker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 17 * * *

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Get KernelSU Version
      id: getKSU
      run: |
        git clone https://github.com/tiann/KernelSU -b main ${GITHUB_WORKSPACE}/KernelSU
        cd ${GITHUB_WORKSPACE}/KernelSU
        echo "KSU=$(($(git rev-list --count HEAD) + 30000))" >> "$GITHUB_OUTPUT"

    - name: Get Kernel Version
      id: getKernel
      run: |
        git clone --depth 1 https://android.googlesource.com/kernel/common -b android12-5.10-lts ${GITHUB_WORKSPACE}/common
        cd ${GITHUB_WORKSPACE}/common
        VERSION=$(grep "^VERSION = .*$" Makefile | awk '{print $3}')
        PATCHLEVEL=$(grep "^PATCHLEVEL = .*$" Makefile | awk '{print $3}')
        SUBLEVEL=$(grep "^SUBLEVEL = .*$" Makefile | awk '{print $3}')
        Kernel_VER="android12-${VERSION}.${PATCHLEVEL}.${SUBLEVEL}"
        Kernel_HEAD=$(git rev-parse HEAD)
        echo "Kernel_VER=${Kernel_VER}" >> "$GITHUB_OUTPUT"
        echo "Kernel_HEAD=${Kernel_HEAD}" >> "$GITHUB_OUTPUT"

    - name: Get Version
      id: getversion
      run: |
        kernel_v=$(curl -skL https://api.github.com/repos/hubbylei/Redmi_K60_China_Files/releases/latest | jq -r .body | grep "Latest Kernel:" | awk -F": " '{print $2}' | awk -F"-" '{print $3}')
        ksu_v=$(curl -skL https://api.github.com/repos/hubbylei/Redmi_K60_China_Files/releases/latest | jq -r .tag_name | awk -F"-" '{print $3}')
        echo "Kernel_VER=${kernel_v}" >> "$GITHUB_OUTPUT"
        echo "KSU_VER=${ksu_v}" >> "$GITHUB_OUTPUT"

    - name: Compare Version
      id: compare
      run: |
        cacheVer=${{ steps.getversion.outputs.KSU_VER }}-${{ steps.getversion.outputs.Kernel_VER }}
        getVer=${{ steps.getKSU.outputs.KSU }}-${{ steps.getKernel.outputs.Kernel_HEAD }}
        echo "CacheVer: $cacheVer"
        echo "GetVer: $getVer"
        if [ "$cacheVer" != "$getVer" ];then
          echo "build=true" >> "$GITHUB_OUTPUT"
        else
          echo "build=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Auto compile
      if: steps.compare.outputs.build == 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: AutoCompile

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 3
